# Generated by Django 5.0.7 on 2024-07-29 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sun time')),
                ('time', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon')], default='M', max_length=1)),
                ('turtle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turtle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
